// ============================================================
// 00. CONCEPTUAL SYSTEM CONTENT
// ============================================================
const SYSTEM_NODES = {
  determinants:{ title:"Wider determinants", summary:"Health is shaped long before someone reaches a health service.", influences:"Income, housing, education, employment, environment, crime, discrimination and social connection.", changes:"Exposure to risk, ability to stay healthy, help-seeking, recovery and healthy life expectancy.", measures:"IMD and its domains, employment, housing, education, crime and environmental indicators.", gaps:"Area measures do not describe every individual and cannot show exactly how determinants produced a particular outcome." },
  risk:{ title:"Risk and prevention", summary:"Risk accumulates across a lifetime, while prevention can delay or avoid some disease.", influences:"Wider determinants, genetics, behaviour, vaccination, screening and preventive treatment.", changes:"Disease incidence, age at onset, severity at diagnosis and later demand.", measures:"Risk-factor prevalence, screening uptake, vaccination, smoking, obesity, blood pressure and prescribing.", gaps:"Prevented events are invisible. Success is often inferred from what did not happen." },
  undiagnosed:{ title:"Condition develops", summary:"Disease can exist before it is recognised by either the person or the health system.", influences:"Underlying risk, disease biology, symptoms, access, testing and clinical thresholds.", changes:"The pool of unmet need and the likelihood of a later crisis or complication.", measures:"Modelled prevalence and selected audit measures can estimate part of the diagnosis gap.", gaps:"We usually cannot identify which specific people have an undiagnosed condition." },
  diagnosis:{ title:"Detection and diagnosis", summary:"Diagnosis makes disease visible and usually increases recorded prevalence.", influences:"Screening, contact with services, continuity, coding, thresholds and patient trust.", changes:"Access to treatment, recorded prevalence, patient identity and future monitoring.", measures:"QOF recorded prevalence, estimated prevalence, detection ratios and register counts.", gaps:"A high recorded rate may mean high burden, good detection, or both." },
  management:{ title:"Ongoing treatment", summary:"Treatment may control disease, prevent complications and help people live longer.", influences:"Workforce, continuity, medicines, adherence, self-management, access and treatment targets.", changes:"Symptoms, crisis risk, quality of life, mortality and the duration people live with conditions.", measures:"QOF achievement, CVDPREVENT, prescribing, reviews and treatment-to-target indicators.", gaps:"Process measures do not fully reveal treatment quality, individual preferences or causal effect." },
  crisis:{ title:"Crisis and acute care", summary:"Acute use reflects both population need and how the rest of the system is functioning.", influences:"Severity, prevention, access, help-seeking, ambulance pathways, bed capacity and admission thresholds.", changes:"Survival, disability, future risk, costs and subsequent service use.", measures:"Attendances, chief complaint, acuity, conversion, admissions, procedures, length of stay and mortality.", gaps:"Hospital-visible disease is not population prevalence. Capacity and demand influence one another." },
  recovery:{ title:"Recovery and adaptation", summary:"After illness or treatment, people may recover fully, adapt, relapse or become more dependent.", influences:"Severity, rehabilitation, community care, housing, informal care and social care.", changes:"Independence, quality of life, readmission, employment and future support needs.", measures:"Readmission, rehabilitation activity, discharge destination, community activity and social-care measures.", gaps:"Quality of recovery and unpaid care are poorly represented in routine health data." },
  living:{ title:"Living longer", summary:"Longer survival is a success, but it changes the future population and its needs.", influences:"Prevention, treatment effectiveness, living conditions and competing causes of death.", changes:"Prevalence, multimorbidity, dependency, healthy life expectancy and lifetime service use.", measures:"Survival, mortality, life expectancy, healthy life expectancy and condition prevalence.", gaps:"More prevalence or future treatment can reflect success rather than system failure." },
  capacity:{ title:"Service capacity", summary:"Capacity affects access, thresholds, queues and what activity the system can record.", influences:"Funding, workforce, infrastructure, historic provision, productivity and cross-boundary flows.", changes:"Waiting, admission decisions, treatment intensity, discharge and apparent demand.", measures:"Workforce, appointments, beds, occupancy, waits, community capacity and social-care supply.", gaps:"Supply can create or reveal demand. Current activity is therefore not a neutral measure of need." },
  "future-demand":{ title:"Future need and demand", summary:"Today’s choices alter tomorrow’s population, disease burden and service requirements.", influences:"Survival, incidence, ageing, migration, disability, prevention and treatment.", changes:"Workforce requirements, costs, capacity choices and the balance between sectors.", measures:"Population projections, prevalence trends, utilisation, bed-days and modelled scenarios.", gaps:"Avoided demand may be delayed rather than permanently removed, and forecasts depend on assumptions." },
  behaviour:{ title:"Access and behaviour", summary:"People do not experience or use the health system in identical ways.", influences:"Trust, health literacy, culture, continuity, cost, convenience, symptoms and prior experience.", changes:"Prevention uptake, time to diagnosis, emergency use, adherence and outcomes.", measures:"Survey results, appointment use, screening uptake, mode of arrival and patterns of attendance.", gaps:"Routine activity cannot reliably explain why someone sought—or did not seek—care." },
  outcomes:{ title:"Outcomes that matter", summary:"Activity is not the final objective. The system ultimately exists to improve lives fairly.", influences:"Every preceding part of the map, plus personal goals and circumstances.", changes:"Future health, participation, demand, public confidence and resource choices.", measures:"Mortality, quality of life, independence, healthy life expectancy, equity and patient-reported outcomes.", gaps:"The outcomes easiest to count are not always those people value most." }
};

// ============================================================
// 01. CONNECTIONS AND INTERVENTIONS
// ============================================================
const SYSTEM_EDGES = [
  ["determinants","risk","context"],["risk","undiagnosed","core"],["undiagnosed","diagnosis","core"],["diagnosis","management","core"],
  ["management","crisis","core"],["crisis","recovery","core"],["recovery","living","core"],["living","future-demand","feedback"],
  ["future-demand","capacity","feedback"],["capacity","diagnosis","context"],["capacity","management","context"],["capacity","crisis","context"],
  ["behaviour","diagnosis","context"],["behaviour","crisis","context"],["management","living","feedback"],["living","management","feedback"],
  ["recovery","outcomes","core"],["living","outcomes","core"],["determinants","outcomes","context"]
];

const INTERVENTIONS = {
  prevention:{ label:"Improve prevention and reduce risk", highlight:["determinants","risk","undiagnosed","future-demand"], intended:"Fewer or later new conditions; longer healthy life.", tradeoff:"Benefits emerge slowly and prevented events are difficult to observe." },
  detection:{ label:"Improve case-finding and diagnosis", highlight:["undiagnosed","diagnosis","management","future-demand"], intended:"More people receive treatment before complications occur.", tradeoff:"Recorded prevalence and immediate treatment demand rise, which can look like deterioration." },
  management:{ label:"Improve long-term condition management", highlight:["management","crisis","living","future-demand"], intended:"Better control, fewer complications and improved survival.", tradeoff:"People may live longer with conditions and require treatment for more years." },
  beds:{ label:"Increase acute bed capacity", highlight:["capacity","crisis","recovery"], intended:"Less crowding and more capacity to admit people who may benefit.", tradeoff:"Admission thresholds may fall; activity and cost can rise without a change in underlying need." },
  community:{ label:"Expand community and social care", highlight:["capacity","recovery","crisis","outcomes"], intended:"Support recovery, independence and alternatives to hospital care.", tradeoff:"Demand may be revealed rather than removed, and savings may appear in a different organisation." }
};

// ============================================================
// 02. ILLUSTRATIVE EVIDENCE NODES
// ============================================================
const EVIDENCE_NODES = [
  { id:"population", label:"Registered population", value:"1.24m", note:"People", status:"measured", interpretation:"A denominator for rates, but registration and resident populations differ." },
  { id:"need", label:"Estimated people living with selected conditions", value:"214k", note:"Modelled", status:"proxy", interpretation:"Estimated burden is independent of diagnosis but depends on model assumptions." },
  { id:"diagnosed", label:"People on QOF registers", value:"176k", note:"Recorded", status:"measured", interpretation:"Recorded prevalence reflects both underlying disease and how effectively conditions are identified." },
  { id:"controlled", label:"Condition appropriately controlled", value:"—", note:"Not consistently comparable", status:"gap", interpretation:"Available treatment indicators differ by condition and do not create one overall measure of good management." },
  { id:"attendance", label:"Emergency attendances", value:"412k", note:"Per year", status:"measured", interpretation:"Attendances reflect need, access, behaviour, ambulance pathways and alternative service availability." },
  { id:"conversion", label:"Attendance resulting in admission", value:"28.6%", note:"Illustrative", status:"proxy", interpretation:"A possible admission-threshold signal, but it also changes with acuity and the mix of people attending." },
  { id:"admissions", label:"Emergency admissions", value:"118k", note:"Per year", status:"measured", interpretation:"Admissions are an output of need, attendance and clinical/capacity decisions—not a direct measure of poor primary care." },
  { id:"severity", label:"Severity before reaching hospital", value:"?", note:"Important unknown", status:"gap", interpretation:"Hospital measures occur after selection into hospital and can make comparisons circular." },
  { id:"bed-days", label:"Emergency bed-days", value:"706k", note:"Per year", status:"measured", interpretation:"Bed-days combine admission volume and length of stay; the same total can arise through very different pathways." },
  { id:"recovery", label:"Quality of recovery", value:"?", note:"Limited routine measurement", status:"gap", interpretation:"Readmission and mortality do not fully describe independence, symptoms or quality of life." },
  { id:"survival", label:"People surviving longer", value:"+3.1 yrs", note:"Illustrative trend", status:"proxy", interpretation:"Longer survival is beneficial but increases the population living with ongoing conditions." },
  { id:"future", label:"Future support requirement", value:"?", note:"Model-dependent", status:"gap", interpretation:"Future need depends on survival, incidence, disability, prevention, migration and service choices." }
];
